sudo: required
language: generic
services:
- docker

install:
- if [ ! -f $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
- sudo ln -s $HOME/.meteor/meteor /usr/bin/meteor

script:
- cd tests && bash run_tests.sh

after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- ./tag_branch.sh
- docker push urbanetic/meteord

env:
  global:
  - secure: mXy9eJUfXzfgw1sMr445iNDdGt3fitc1jVvDm+65jl/BXMmQdr/kHZQeAODfPPqLf6cPY7OPgdGYCmvqSerOSil8nw4RKo81ozQ43tC0Wu/bNUQ0UweMtj0/EyJAce11f9GRmQARcuZxk/BgDKwes/61dRJS/shPxHq8YShwlO0yI/WvOmnDvStQlTHza91wxvjcD2VuLsWf6U8+G75L4a7nZdAjmlVT5IN/BZYuTScjTqp00ZrtbojjFT/bvN/wkpnn3hOPgQg5XUOGfK2YzZo1A7b53ixBfjIWyHtgny8vRnD/donJQ7maoZUQRcOq/1AFUO5NN9odEQq/SBcOs2RfzfswvI1GeFq6DLQLpG3dfy4YJ2F5fBQtG3NZTSq1tW57O6XczN4N2dHCs9M11mNRupGi4TKCiYkh/Xrp0C2nZgNwsTngryUYogk4PR8cm6thRxoNQu/JQz2wGZr8NXTJudqIuUUAiYXb31nwFI/RZ/HgBIRNi5MdF9PC8OM18jkkuGUnPGRmdRhjdpOuWcw25P8w4LRxvRA9huHJ3UIcgW1bWmm2/w6hyuVjw30V8KEQdyL15WmOtj9gfAc7zXjqDMBr6tOTNdQurxoYMrqHFIQnsPImkl2BQptny6kCGqN+nfH/K1fXd0N2fDapowG6Q6BXiwuCxJIjI3+GnrE=
  - secure: nyoZB4gvF1pCVdEjPPF0/8yqCcE2pR8NEYfeqhKuL3PFpmlKTOcJTIlqsFlBTuQmt2O9S/Ty+ZsNxfsgQq3SjP20CNQpZL3ys4YGersQ0ds8gmn2MsNWZdJDHY5Rh2hTqIasKEi/pjnxeXhvrIy51iWATfPLBBOM18Q1N+NsvXRwPHzvJOPZcT705fpiGSWipSvGKtzZlbpW/4hpsnTVN76n7wxJg+CwcluDoSgvcMt1LjP1wZuYi8J2vEy7Mqgb4/qAonaL0e/vhsnXUfOmLuLHIT6lduhbFbhKkjxqTvHJSaWtsyZkaCShFskuwd8miuhR4V+IoHAZCvuvZpxBdWNs24W6n8+ebf3D/+bb/IMF3+B4s0q1zC2o3bB9ug7ylyIURf/Ikvfyibwuh40Pa0otGOzpiRr7IZBLqFdlS04EWg6Je3n+/AHMhNmfvFasOWTyZqiC5f6wI0d2019jZYy82nyx+BCryy+UAskOZ6HG5i+YRkG74rONdyzwIMJPgPNLKvP5+1xbsigi1G0Ul2HDaDB9CkHdZV/KaQdtjdL/odWa726dCsoTGxriWl7PqtXWRxbCt3/uhPo4L8AyNipUCluWX/kWYhWpAxznmhEvgPcRziJtGacU81PQ3nYLhp4Kc/O5pj7EkUrxO6+3FOrZ5P72pfn5HFB1Hs9Ho2k=
  - secure: ZmcIM+z95CYrmi0h+hps96mNVa8h9i1ssvbqwkNtm9mHfi4rFPdl33EVx/zynTCdyOaAJpn7y3vwfBP8PKTqeZUMnsqp7urNMPr7EhhGmOMYE7mxB7XhrQFImTEnn8NMAPoth+2ssASqCwAzAWUUHUFJc/An9KIazafrGOqibpPTGCK1mJ4meqTm+0M+6Q5K+W5fhZ/WmVK+XIFh/62BjvzYnNJTi/BMpc0kpVu2PX1mWXxaa2lUVOHBTE4a5QrTjNdtHvBf+I5kzAJ3753SN/3y3dVLVfOvRmGcHmG8HGJsl9x0SAHNHeYlmVbkWlUD21MiFBtrllPsMDDmwtTQv7zDnDmJNbK2Dfw484HVSJwhz/WiPpR6aRzdmvs6uSjFddVMJz2UWBTIOrboaNFJUZxvQPJAiLGoH6T6PgdpL76NBT47TgGa/dKTOhDLtLIqnEGQ1uI/G1a04+bDYrJg8TgM8qdM9jnPh9lcWC9w9rrB/le96dHT3As+yAfEWDJA1dDtDnZNBgQbD7K0hMdNpClcsd6Z/SMkObWzpctVULBUblYQ4NU+XzBwMNOOmdhjh6XtD573Zpn4tMILTY+m8F+FVG7/yNvmo2mWojf+wzRoGUuaIj7QrHDPxAvLJYIuh3V0Pg02QOBnM7bJCv3FzWtkR7Uy1a7SlQO3deY4mGg=
